micronaut:
  application:
    name: keyManager

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/key-manager-db
    driverClassName: org.postgresql.Driver
    username: keycloak
    password: password
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

contas:
  itau:
    url: 'http://localhost:9091'

pix:
  bcb:
    url: 'http://localhost:8082'